name: Build and Test (Main)
on:
  pull_request:
    branches:
      - main # ou a branch que deseja implantar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v3
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build
      uses: gradle/gradle-build-action@v2.1.5
      with:
        arguments: bootJar
        
    - name: Test
      uses: gradle/gradle-build-action@v2.1.5
      with:
        arguments: 'test --info'

    - uses: actions/upload-artifact@v3
      with:
        path: ./*/*/*.jar
        if-no-files-found: error